// playgrounds/react-vite/src/pages/PlanetsPage.tsx
import { useState, useEffect } from 'react'
import LoadingOrbit from '../components/LoadingOrbit'

interface Planet {
  id: number
  name: string
  type: string
  radius_km: number
  gravity_ms2: number
  avg_temp_c: number
  moons: number
  distance_from_sun_mkm: number
  orbital_period_days: number
  discovered_by: string
  description: string
  color: string
}

const containerStyle: React.CSSProperties = {}

const headingStyle: React.CSSProperties = {
  fontSize: '28px',
  fontWeight: 700,
  marginBottom: '8px',
  color: '#e0e6f0',
}

const subtitleStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#64748b',
  marginBottom: '32px',
}

const tableWrapperStyle: React.CSSProperties = {
  overflowX: 'auto',
  borderRadius: '10px',
  border: '1px solid #1e293b',
  backgroundColor: '#111827',
}

const tableStyle: React.CSSProperties = {
  width: '100%',
  borderCollapse: 'collapse',
  fontSize: '14px',
}

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  padding: '14px 20px',
  borderBottom: '1px solid #1e293b',
  color: '#94a3b8',
  fontWeight: 600,
  fontSize: '12px',
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
}

const tdStyle: React.CSSProperties = {
  padding: '14px 20px',
  borderBottom: '1px solid #1e293b',
  color: '#cbd5e1',
}

const nameStyle: React.CSSProperties = {
  ...tdStyle,
  fontWeight: 600,
  color: '#e0e6f0',
}

const nameCellStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '10px',
}

const typeBadgeBase: React.CSSProperties = {
  display: 'inline-block',
  padding: '3px 10px',
  borderRadius: '9999px',
  fontSize: '12px',
  fontWeight: 500,
}

const loadingStyle: React.CSSProperties = {
  fontSize: '16px',
  color: '#94a3b8',
  padding: '40px 0',
  textAlign: 'center',
}

const errorStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#f87171',
  backgroundColor: '#1c1017',
  border: '1px solid #7f1d1d',
  borderRadius: '10px',
  padding: '20px 24px',
}

function getTypeBadgeStyle(type: string): React.CSSProperties {
  switch (type) {
    case 'Terrestrial':
      return { ...typeBadgeBase, backgroundColor: '#064e3b', color: '#6ee7b7' }
    case 'Gas Giant':
      return { ...typeBadgeBase, backgroundColor: '#4c1d95', color: '#c4b5fd' }
    case 'Ice Giant':
      return { ...typeBadgeBase, backgroundColor: '#1e3a5f', color: '#7dd3fc' }
    case 'Dwarf':
      return { ...typeBadgeBase, backgroundColor: '#3b1a00', color: '#fdba74' }
    default:
      return { ...typeBadgeBase, backgroundColor: '#1e293b', color: '#94a3b8' }
  }
}

function formatDistance(mkm: number): string {
  if (mkm >= 1000) {
    return `${(mkm / 1000).toFixed(1)}B km`
  }
  return `${mkm.toFixed(1)}M km`
}

function PlanetsPage() {
  const [planets, setPlanets] = useState<Planet[]>([])
  const [total, setTotal] = useState<number>(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/planets')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to fetch planets (${res.status})`)
        return res.json()
      })
      .then((data) => {
        setPlanets(data.planets)
        setTotal(data.total)
        setLoading(false)
      })
      .catch((err) => {
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Planets</h1>
        <LoadingOrbit />
      </div>
    )
  }

  if (error) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Planets</h1>
        <div style={errorStyle}>Error: {error}</div>
      </div>
    )
  }

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Planets</h1>
      <p style={subtitleStyle}>{total} planets in the solar system</p>

      <div style={tableWrapperStyle}>
        <table style={tableStyle}>
          <thead>
            <tr>
              <th style={thStyle}>Name</th>
              <th style={thStyle}>Type</th>
              <th style={thStyle}>Distance</th>
              <th style={thStyle}>Radius</th>
              <th style={thStyle}>Moons</th>
              <th style={thStyle}>Gravity</th>
            </tr>
          </thead>
          <tbody>
            {planets.map((planet, index) => (
              <tr
                key={planet.id}
                style={{
                  backgroundColor: index % 2 === 0 ? 'transparent' : '#0d1322',
                }}
              >
                <td style={nameStyle}>
                  <div style={nameCellStyle}>
                    <span
                      style={{
                        width: '10px',
                        height: '10px',
                        borderRadius: '50%',
                        backgroundColor: planet.color,
                        flexShrink: 0,
                      }}
                    />
                    {planet.name}
                  </div>
                </td>
                <td style={tdStyle}>
                  <span style={getTypeBadgeStyle(planet.type)}>{planet.type}</span>
                </td>
                <td style={tdStyle}>{formatDistance(planet.distance_from_sun_mkm)}</td>
                <td style={tdStyle}>{planet.radius_km.toLocaleString()} km</td>
                <td style={tdStyle}>{planet.moons}</td>
                <td style={tdStyle}>{planet.gravity_ms2} m/s²</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default PlanetsPage

// playgrounds/svelte-vite/src/components/PlanetsPage.svelte
<script lang="ts">
  let planets = $state<any[]>([])
  let loading = $state(true)
  let error = $state('')

  $effect(() => {
    fetch('/api/planets')
      .then(r => r.json())
      .then(data => { planets = data.planets; loading = false })
      .catch(e => { error = e.message; loading = false })
  })
</script>

<section class="planets-page">
  <h2 class="page-title">Planets</h2>
  <p class="page-desc">Explore the planets of our solar system and beyond.</p>

  {#if loading}
    <p class="status-msg">Loading...</p>
  {:else if error}
    <p class="status-msg error">Error: {error}</p>
  {:else}
    <div class="table-wrapper">
      <table class="planet-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Distance (M km)</th>
            <th>Radius (km)</th>
            <th>Moons</th>
            <th>Temp (&deg;C)</th>
          </tr>
        </thead>
        <tbody>
          {#each planets as planet}
            <tr>
              <td class="planet-name">
                <span class="color-dot" style="background-color: {planet.color}"></span>
                {planet.name}
              </td>
              <td>{planet.type}</td>
              <td>{planet.distance_from_sun_mkm}</td>
              <td>{planet.radius_km.toLocaleString()}</td>
              <td>{planet.moons}</td>
              <td>{planet.avg_temp_c}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>

<style>
  .planets-page {
    animation: fadeIn 0.3s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .page-title {
    font-size: 1.75rem;
    color: #e2e8f0;
    margin: 0 0 0.5rem 0;
  }

  .page-desc {
    color: #7a8fa3;
    margin: 0 0 2rem 0;
    font-size: 1rem;
  }

  .status-msg {
    color: #c8d6e5;
    font-size: 1rem;
    padding: 2rem;
    text-align: center;
  }

  .status-msg.error {
    color: #f87171;
  }

  .table-wrapper {
    overflow-x: auto;
    border-radius: 8px;
    border: 1px solid #2e1c4f;
  }

  .planet-table {
    width: 100%;
    border-collapse: collapse;
    min-width: 700px;
  }

  .planet-table thead {
    background-color: #271d2f;
  }

  .planet-table th {
    padding: 0.875rem 1.25rem;
    text-align: left;
    font-weight: 600;
    color: #7020b1;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 2px solid #2e1c4f;
  }

  .planet-table td {
    padding: 0.875rem 1.25rem;
    border-bottom: 1px solid #322447;
    color: #a0b3c6;
    font-size: 0.95rem;
  }

  .planet-table tbody tr:hover {
    background-color: #322541;
  }

  .planet-table tbody tr:last-child td {
    border-bottom: none;
  }

  .planet-name {
    color: #e2e8f0;
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }

  .color-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
    flex-shrink: 0;
  }
</style>
