// playgrounds/svelte-vite/src/components/MoonsPage.svelte
<script lang="ts">
  let moons = $state<any[]>([])
  let loading = $state(true)
  let error = $state('')

  $effect(() => {
    fetch('/api/moons')
      .then(r => r.json())
      .then(data => { moons = data.moons; loading = false })
      .catch(e => { error = e.message; loading = false })
  })
</script>

<section class="moons-page">
  <h2 class="page-title">Moons</h2>
  <p class="page-desc">Discover the natural satellites orbiting the planets of our solar system.</p>

  {#if loading}
    <p class="status-msg">Loading...</p>
  {:else if error}
    <p class="status-msg error">Error: {error}</p>
  {:else}
    <div class="table-wrapper">
      <table class="moon-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Planet</th>
            <th>Radius (km)</th>
            <th>Orbital Period (days)</th>
            <th>Discovered By</th>
            <th>Year</th>
          </tr>
        </thead>
        <tbody>
          {#each moons as moon}
            <tr>
              <td class="moon-name">
                <span class="color-dot" style="background-color: {moon.color}"></span>
                {moon.name}
              </td>
              <td><span class="moon-planet">{moon.planet}</span></td>
              <td>{moon.radius_km.toLocaleString()}</td>
              <td>{moon.orbital_period_days}</td>
              <td>{moon.discovered_by}</td>
              <td>{moon.year_discovered}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>

<style>
  .moons-page {
    animation: fadeIn 0.3s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .page-title {
    font-size: 1.75rem;
    color: #e2e8f0;
    margin: 0 0 0.5rem 0;
  }

  .page-desc {
    color: #7a8fa3;
    margin: 0 0 2rem 0;
    font-size: 1rem;
  }

  .status-msg {
    color: #c8d6e5;
    font-size: 1rem;
    padding: 2rem;
    text-align: center;
  }

  .status-msg.error {
    color: #f87171;
  }

  .table-wrapper {
    overflow-x: auto;
    border-radius: 8px;
    border: 1px solid #2e1c4f;
  }

  .moon-table {
    width: 100%;
    border-collapse: collapse;
    min-width: 700px;
  }

  .moon-table thead {
    background-color: #271d2f;
  }

  .moon-table th {
    padding: 0.875rem 1.25rem;
    text-align: left;
    font-weight: 600;
    color: #7020b1;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 2px solid #2e1c4f;
  }

  .moon-table td {
    padding: 0.875rem 1.25rem;
    border-bottom: 1px solid #322447;
    color: #a0b3c6;
    font-size: 0.95rem;
  }

  .moon-table tbody tr:hover {
    background-color: #322541;
  }

  .moon-table tbody tr:last-child td {
    border-bottom: none;
  }

  .moon-name {
    color: #e2e8f0;
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }

  .color-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
    flex-shrink: 0;
  }

  .moon-planet {
    font-size: 0.75rem;
    color: #7020b1;
    background-color: #6a6b43;
    padding: 0.2rem 0.6rem;
    border-radius: 12px;
    border: 1px solid #1e1330;
    white-space: nowrap;
  }
</style>

// playgrounds/react-vite/src/pages/MoonsPage.tsx
import { useState, useEffect } from 'react'
import LoadingOrbit from '../components/LoadingOrbit'

interface Moon {
  id: number
  name: string
  planet: string
  radius_km: number
  distance_km: number
  orbital_period_days: number
  discovered_by: string
  year_discovered: number
  description: string
  color: string
}

const containerStyle: React.CSSProperties = {}

const headingStyle: React.CSSProperties = {
  fontSize: '28px',
  fontWeight: 700,
  marginBottom: '8px',
  color: '#e0e6f0',
}

const subtitleStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#64748b',
  marginBottom: '32px',
}

const tableWrapperStyle: React.CSSProperties = {
  overflowX: 'auto',
  borderRadius: '10px',
  border: '1px solid #1e293b',
  backgroundColor: '#111827',
}

const tableStyle: React.CSSProperties = {
  width: '100%',
  borderCollapse: 'collapse',
  fontSize: '14px',
}

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  padding: '14px 20px',
  borderBottom: '1px solid #1e293b',
  color: '#94a3b8',
  fontWeight: 600,
  fontSize: '12px',
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
}

const tdStyle: React.CSSProperties = {
  padding: '14px 20px',
  borderBottom: '1px solid #1e293b',
  color: '#cbd5e1',
}

const nameStyle: React.CSSProperties = {
  ...tdStyle,
  fontWeight: 600,
  color: '#e0e6f0',
}

const nameCellStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '10px',
}

const planetBadgeStyle: React.CSSProperties = {
  fontSize: '13px',
  color: '#a78bfa',
  fontWeight: 500,
}

const loadingStyle: React.CSSProperties = {
  fontSize: '16px',
  color: '#94a3b8',
  padding: '40px 0',
  textAlign: 'center',
}

const errorStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#f87171',
  backgroundColor: '#1c1017',
  border: '1px solid #7f1d1d',
  borderRadius: '10px',
  padding: '20px 24px',
}

function MoonsPage() {
  const [moons, setMoons] = useState<Moon[]>([])
  const [total, setTotal] = useState<number>(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/moons')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to fetch moons (${res.status})`)
        return res.json()
      })
      .then((data) => {
        setMoons(data.moons)
        setTotal(data.total)
        setLoading(false)
      })
      .catch((err) => {
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Moons</h1>
        <LoadingOrbit />
      </div>
    )
  }

  if (error) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Moons</h1>
        <div style={errorStyle}>Error: {error}</div>
      </div>
    )
  }

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Moons</h1>
      <p style={subtitleStyle}>{total} moons across the solar system</p>

      <div style={tableWrapperStyle}>
        <table style={tableStyle}>
          <thead>
            <tr>
              <th style={thStyle}>Name</th>
              <th style={thStyle}>Planet</th>
              <th style={thStyle}>Radius</th>
              <th style={thStyle}>Orbital Period</th>
              <th style={thStyle}>Discovered By</th>
              <th style={thStyle}>Year</th>
            </tr>
          </thead>
          <tbody>
            {moons.map((moon, index) => (
              <tr
                key={moon.id}
                style={{
                  backgroundColor: index % 2 === 0 ? 'transparent' : '#0d1322',
                }}
              >
                <td style={nameStyle}>
                  <div style={nameCellStyle}>
                    <span
                      style={{
                        width: '10px',
                        height: '10px',
                        borderRadius: '50%',
                        backgroundColor: moon.color,
                        flexShrink: 0,
                      }}
                    />
                    {moon.name}
                  </div>
                </td>
                <td style={tdStyle}>
                  <span style={planetBadgeStyle}>{moon.planet}</span>
                </td>
                <td style={tdStyle}>{moon.radius_km.toLocaleString()} km</td>
                <td style={tdStyle}>{moon.orbital_period_days} days</td>
                <td style={tdStyle}>{moon.discovered_by}</td>
                <td style={tdStyle}>{moon.year_discovered}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default MoonsPage
