// playgrounds/svelte-vite/src/components/StatsPage.svelte
<script lang="ts">
  let stats = $state<any>(null)
  let loading = $state(true)
  let error = $state('')

  $effect(() => {
    fetch('/api/stats')
      .then(r => r.json())
      .then(data => { stats = data; loading = false })
      .catch(e => { error = e.message; loading = false })
  })
</script>

<section class="stats-page">
  <h2 class="page-title">Solar System Stats</h2>
  <p class="page-desc">Key statistics about our solar system at a glance.</p>

  {#if loading}
    <p class="status-msg">Loading...</p>
  {:else if error}
    <p class="status-msg error">Error: {error}</p>
  {:else if stats}
    <div class="stats-grid">
      <div class="stat-card">
        <span class="stat-value">{stats.total_planets}</span>
        <span class="stat-label">Total Planets</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{stats.total_moons}</span>
        <span class="stat-label">Total Moons</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{stats.largest_planet}</span>
        <span class="stat-label">Largest Planet</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{stats.smallest_planet}</span>
        <span class="stat-label">Smallest Planet</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{stats.hottest_planet}</span>
        <span class="stat-label">Hottest Planet</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{stats.coldest_planet}</span>
        <span class="stat-label">Coldest Planet</span>
      </div>
    </div>
  {/if}
</section>

<style>
  .stats-page {
    animation: fadeIn 0.3s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .page-title {
    font-size: 1.75rem;
    color: #e2e8f0;
    margin: 0 0 0.5rem 0;
  }

  .page-desc {
    color: #7a8fa3;
    margin: 0 0 2rem 0;
    font-size: 1rem;
  }

  .status-msg {
    color: #c8d6e5;
    font-size: 1rem;
    padding: 2rem;
    text-align: center;
  }

  .status-msg.error {
    color: #f87171;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 1.25rem;
  }

  .stat-card {
    background-color: #424952;
    border: 1px solid #2e1c4f;
    border-radius: 8px;
    padding: 1.5rem;
    text-align: center;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    transition: border-color 0.2s ease, transform 0.2s ease;
  }

  .stat-card:hover {
    border-color: #201d49;
    transform: translateY(-2px);
  }

  .stat-value {
    font-size: 1.75rem;
    font-weight: 700;
    color: #7020b1;
    word-break: break-word;
  }

  .stat-label {
    font-size: 0.8rem;
    color: #5a7a96;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
</style>

// playgrounds/react-vite/src/pages/StatsPage.tsx
import { useState, useEffect } from 'react'
import LoadingOrbit from '../components/LoadingOrbit'

interface Stats {
  total_planets: number
  total_moons: number
  largest_planet: string
  smallest_planet: string
  hottest_planet: string
  coldest_planet: string
}

const containerStyle: React.CSSProperties = {}

const headingStyle: React.CSSProperties = {
  fontSize: '28px',
  fontWeight: 700,
  marginBottom: '8px',
  color: '#e0e6f0',
}

const subtitleStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#64748b',
  marginBottom: '32px',
}

const gridStyle: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
  gap: '20px',
}

const cardStyle: React.CSSProperties = {
  backgroundColor: '#111827',
  border: '1px solid #1e293b',
  borderRadius: '10px',
  padding: '28px',
}

const cardLabelStyle: React.CSSProperties = {
  fontSize: '13px',
  color: '#64748b',
  fontWeight: 500,
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
  marginBottom: '8px',
}

const cardValueStyle: React.CSSProperties = {
  fontSize: '28px',
  fontWeight: 700,
  color: '#e0e6f0',
}

const cardValueSmallStyle: React.CSSProperties = {
  fontSize: '22px',
  fontWeight: 700,
  color: '#e0e6f0',
}

const loadingStyle: React.CSSProperties = {
  fontSize: '16px',
  color: '#94a3b8',
  padding: '40px 0',
  textAlign: 'center',
}

const errorStyle: React.CSSProperties = {
  fontSize: '15px',
  color: '#f87171',
  backgroundColor: '#1c1017',
  border: '1px solid #7f1d1d',
  borderRadius: '10px',
  padding: '20px 24px',
}

function StatsPage() {
  const [stats, setStats] = useState<Stats | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/stats')
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to fetch stats (${res.status})`)
        return res.json()
      })
      .then((data) => {
        setStats(data)
        setLoading(false)
      })
      .catch((err) => {
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Stats</h1>
        <LoadingOrbit />
      </div>
    )
  }

  if (error) {
    return (
      <div style={containerStyle}>
        <h1 style={headingStyle}>Stats</h1>
        <div style={errorStyle}>Error: {error}</div>
      </div>
    )
  }

  if (!stats) return null

  const statCards = [
    { label: 'Total Planets', value: stats.total_planets, large: true },
    { label: 'Total Moons', value: stats.total_moons, large: true },
    { label: 'Largest Planet', value: stats.largest_planet, large: false },
    { label: 'Smallest Planet', value: stats.smallest_planet, large: false },
    { label: 'Hottest Planet', value: stats.hottest_planet, large: false },
    { label: 'Coldest Planet', value: stats.coldest_planet, large: false },
  ]

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Stats</h1>
      <p style={subtitleStyle}>Solar system at a glance</p>

      <div style={gridStyle}>
        {statCards.map((card) => (
          <div key={card.label} style={cardStyle}>
            <div style={cardLabelStyle}>{card.label}</div>
            <div style={card.large ? cardValueStyle : cardValueSmallStyle}>
              {card.value}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default StatsPage
