// playgrounds/svelte-vite/src/App.svelte
<script lang="ts">
  import Header from './components/Header.svelte'
  import PlanetsPage from './components/PlanetsPage.svelte'
  import MoonsPage from './components/MoonsPage.svelte'
  import StatsPage from './components/StatsPage.svelte'

  let currentPage = $state('planets')

  function navigate(page: string) {
    currentPage = page
  }
</script>

<div class="app">
  <Header {currentPage} onNavigate={navigate} />
  <main class="content">
    {#if currentPage === 'planets'}
      <PlanetsPage />
    {:else if currentPage === 'moons'}
      <MoonsPage />
    {:else if currentPage === 'stats'}
      <StatsPage />
    {/if}
  </main>
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, sans-serif;
    background-color: #161718;
    color: #c8d6e5;
  }

  :global(*) {
    box-sizing: border-box;
  }

  .app {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }

  .content {
    flex: 1;
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
    width: 100%;
  }
</style>

// playgrounds/vue-webpack/src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue'
</script>

<template>
  <div class="app">
    <Header />
    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg: #0c1222;
  --surface: #131b2e;
  --surface-2: #1a2540;
  --border: #243049;
  --text: #e2e8f0;
  --text-muted: #64748b;
  --accent: #3b82f6;
}

html, body, #app { min-height: 100vh; background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }

.app { min-height: 100vh; }
.main-content { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
</style>
