// playgrounds/svelte-vite/src/components/PlanetsPage.svelte
<script lang="ts">
  let planets = $state<any[]>([])
  let loading = $state(true)
  let error = $state('')

  $effect(() => {
    fetch('/api/planets')
      .then(r => r.json())
      .then(data => { planets = data.planets; loading = false })
      .catch(e => { error = e.message; loading = false })
  })
</script>

<section class="planets-page">
  <h2 class="page-title">Planets</h2>
  <p class="page-desc">Explore the planets of our solar system and beyond.</p>

  {#if loading}
    <p class="status-msg">Loading...</p>
  {:else if error}
    <p class="status-msg error">Error: {error}</p>
  {:else}
    <div class="table-wrapper">
      <table class="planet-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Distance (M km)</th>
            <th>Radius (km)</th>
            <th>Moons</th>
            <th>Temp (&deg;C)</th>
          </tr>
        </thead>
        <tbody>
          {#each planets as planet}
            <tr>
              <td class="planet-name">
                <span class="color-dot" style="background-color: {planet.color}"></span>
                {planet.name}
              </td>
              <td>{planet.type}</td>
              <td>{planet.distance_from_sun_mkm}</td>
              <td>{planet.radius_km.toLocaleString()}</td>
              <td>{planet.moons}</td>
              <td>{planet.avg_temp_c}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>

<style>
  .planets-page {
    animation: fadeIn 0.3s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .page-title {
    font-size: 1.75rem;
    color: #e2e8f0;
    margin: 0 0 0.5rem 0;
  }

  .page-desc {
    color: #7a8fa3;
    margin: 0 0 2rem 0;
    font-size: 1rem;
  }

  .status-msg {
    color: #c8d6e5;
    font-size: 1rem;
    padding: 2rem;
    text-align: center;
  }

  .status-msg.error {
    color: #f87171;
  }

  .table-wrapper {
    overflow-x: auto;
    border-radius: 8px;
    border: 1px solid #2e1c4f;
  }

  .planet-table {
    width: 100%;
    border-collapse: collapse;
    min-width: 700px;
  }

  .planet-table thead {
    background-color: #271d2f;
  }

  .planet-table th {
    padding: 0.875rem 1.25rem;
    text-align: left;
    font-weight: 600;
    color: #7020b1;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 2px solid #2e1c4f;
  }

  .planet-table td {
    padding: 0.875rem 1.25rem;
    border-bottom: 1px solid #322447;
    color: #a0b3c6;
    font-size: 0.95rem;
  }

  .planet-table tbody tr:hover {
    background-color: #322541;
  }

  .planet-table tbody tr:last-child td {
    border-bottom: none;
  }

  .planet-name {
    color: #e2e8f0;
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }

  .color-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
    flex-shrink: 0;
  }
</style>

// playgrounds/mfe-vite/src/pages/PlanetsPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import type { Planet } from '../types'

const planets = ref<Planet[]>([])
const search = ref('')
const selected = ref<Planet | null>(null)
const error = ref('')

onMounted(async () => {
  try {
    const res = await fetch('/api/planets')
    planets.value = (await res.json()).planets
  } catch {
    error.value = 'Failed to load planets — is the API running on port 8888?'
  }
})

const filtered = computed(() => {
  const q = search.value.toLowerCase()
  if (!q) return planets.value
  return planets.value.filter(p => p.name.toLowerCase().includes(q) || p.type.toLowerCase().includes(q))
})

function formatTemp(t: number) {
  return t > 0 ? `+${t}°C` : `${t}°C`
}
</script>

<template>
  <div class="planets-page">
    <h1 class="page-title">Planets</h1>

    <div v-if="error" class="error">{{ error }}</div>

    <template v-else>
      <input v-model="search" class="search" type="text" placeholder="Search planets..." />

      <div class="layout">
        <table class="table">
          <thead>
            <tr>
              <th>Planet</th>
              <th>Type</th>
              <th>Radius</th>
              <th>Gravity</th>
              <th>Temp</th>
              <th>Moons</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="p in filtered" :key="p.id"
              :class="{ active: selected?.id === p.id }"
              @click="selected = p"
            >
              <td class="name-cell">
                <span class="dot" :style="{ background: p.color }"></span>
                {{ p.name }}
              </td>
              <td><span class="type-tag">{{ p.type }}</span></td>
              <td>{{ p.radius_km.toLocaleString() }} km</td>
              <td>{{ p.gravity_ms2 }} m/s²</td>
              <td :class="p.avg_temp_c > 100 ? 'hot' : p.avg_temp_c < -100 ? 'cold' : ''">
                {{ formatTemp(p.avg_temp_c) }}
              </td>
              <td>{{ p.moons }}</td>
            </tr>
          </tbody>
        </table>

        <aside v-if="selected" class="detail">
          <button class="close-btn" @click="selected = null">✕</button>
          <div class="detail-dot" :style="{ background: selected.color }"></div>
          <h2>{{ selected.name }}</h2>
          <p class="detail-type">{{ selected.type }}</p>
          <p class="detail-desc">{{ selected.description }}</p>
          <dl class="detail-grid">
            <div><dt>Distance</dt><dd>{{ selected.distance_from_sun_mkm }} Mkm</dd></div>
            <div><dt>Orbital Period</dt><dd>{{ selected.orbital_period_days.toLocaleString() }} days</dd></div>
            <div><dt>Moons</dt><dd>{{ selected.moons }}</dd></div>
            <div><dt>Avg Temp</dt><dd>{{ formatTemp(selected.avg_temp_c) }}</dd></div>
          </dl>
        </aside>
      </div>
    </template>
  </div>
</template>

<style scoped>
.page-title { font-size: 22px; font-weight: 700; margin-bottom: 16px; }
.error {
  padding: 14px 18px;
  background: rgba(245, 91, 91, 0.1);
  border: 1px solid rgba(245, 91, 91, 0.3);
  border-radius: var(--radius);
  color: #fca5a5;
  font-size: 14px;
}
.search {
  width: 100%;
  padding: 10px 14px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  color: var(--text);
  font-size: 13px;
  margin-bottom: 16px;
  outline: none;
}
.search:focus { border-color: var(--accent); }
.layout { display: flex; gap: 20px; align-items: flex-start; }
.table {
  flex: 1;
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.table th {
  text-align: left;
  padding: 10px 12px;
  background: var(--surface);
  color: var(--text-dim);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  border-bottom: 1px solid var(--border);
}
.table td {
  padding: 10px 12px;
  border-bottom: 1px solid var(--border);
}
.table tr { cursor: pointer; transition: background 0.1s; }
.table tbody tr:hover { background: var(--surface-hover); }
.table tr.active { background: var(--accent-dim); }
.name-cell { display: flex; align-items: center; gap: 8px; font-weight: 600; }
.dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
.type-tag {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 4px;
  background: var(--surface-hover);
  color: var(--text-dim);
}
.hot { color: var(--warning); }
.cold { color: var(--accent); }

.detail {
  width: 300px;
  flex-shrink: 0;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 20px;
  position: relative;
}
.close-btn {
  position: absolute;
  top: 12px;
  right: 12px;
  background: none;
  border: none;
  color: var(--text-dim);
  cursor: pointer;
  font-size: 16px;
}
.detail-dot { width: 40px; height: 40px; border-radius: 50%; margin-bottom: 12px; }
.detail h2 { font-size: 18px; margin-bottom: 4px; }
.detail-type { color: var(--text-dim); font-size: 12px; margin-bottom: 12px; }
.detail-desc { font-size: 13px; line-height: 1.5; color: var(--text-dim); margin-bottom: 16px; }
.detail-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}
.detail-grid dt { font-size: 11px; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.04em; }
.detail-grid dd { font-size: 14px; font-weight: 600; margin: 2px 0 0; }

@media (max-width: 800px) {
  .layout { flex-direction: column; }
  .detail { width: 100%; }
}
</style>
