// playgrounds/vue-primevue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import Checkbox from 'primevue/checkbox'
import Select from 'primevue/select'
import Slider from 'primevue/slider'
import Tag from 'primevue/tag'
import Badge from 'primevue/badge'
import ProgressBar from 'primevue/progressbar'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'

const name = ref('')
const agree = ref(false)
const severity = ref('primary')
const volume = ref(40)

const severities = [
  { label: 'Primary', value: 'primary' },
  { label: 'Secondary', value: 'secondary' },
  { label: 'Success', value: 'success' },
  { label: 'Warn', value: 'warn' },
  { label: 'Danger', value: 'danger' },
  { label: 'Info', value: 'info' },
]

const products = ref([
  { id: 1, name: 'Zeus', status: 'active', price: '$29' },
  { id: 2, name: 'Hermes', status: 'paused', price: '$49' },
  { id: 3, name: 'Atlas', status: 'active', price: '$99' },
])
</script>

<template>
  <div class="page">
    <header class="hero">
      <h1>Annotask × PrimeVue Playground</h1>
      <p>A test-bed for component discovery against a real component library.</p>
    </header>

    <Card class="demo-card">
      <template #title>Form controls</template>
      <template #content>
        <div class="form-grid">
          <label>
            <span>Name</span>
            <InputText v-model="name" placeholder="Your name" />
          </label>
          <label>
            <span>Severity</span>
            <Select v-model="severity" :options="severities" optionLabel="label" optionValue="value" placeholder="Pick one" />
          </label>
          <label class="inline">
            <Checkbox v-model="agree" binary inputId="agree" />
            <span>I agree to the terms</span>
          </label>
          <label>
            <span>Volume — {{ volume }}</span>
            <Slider v-model="volume" :min="0" :max="100" />
          </label>
        </div>
      </template>
      <template #footer>
        <div class="actions">
          <Button label="Cancel" severity="secondary" outlined />
          <Button :label="`Submit (${severity})`" :severity="severity" />
        </div>
      </template>
    </Card>

    <Card class="demo-card">
      <template #title>Status indicators</template>
      <template #content>
        <div class="badges">
          <Tag value="Primary" />
          <Tag value="Success" severity="success" />
          <Tag value="Warn" severity="warn" />
          <Tag value="Danger" severity="danger" />
          <Badge value="4" />
          <Badge value="12" severity="success" />
          <ProgressBar :value="volume" />
        </div>
      </template>
    </Card>

    <Card class="demo-card">
      <template #title>DataTable</template>
      <template #content>
        <DataTable :value="products" tableStyle="min-width: 20rem">
          <Column field="id" header="ID" />
          <Column field="name" header="Name" />
          <Column field="status" header="Status">
            <template #body="slotProps">
              <Tag :value="slotProps.data.status" :severity="slotProps.data.status === 'active' ? 'success' : 'warn'" />
            </template>
          </Column>
          <Column field="price" header="Price" />
        </DataTable>
      </template>
    </Card>
  </div>
</template>

<style>
body { margin: 0; font-family: system-ui, -apple-system, sans-serif; background: #0b0d10; color: #e7eaef; }
.page { max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; display: flex; flex-direction: column; gap: 20px; }
.hero h1 { margin: 0 0 6px; font-size: 24px; font-weight: 700; }
.hero p { margin: 0; color: #9ba3af; font-size: 14px; }
.demo-card { background: #141821; border: 1px solid #232a36; }
.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.form-grid label { display: flex; flex-direction: column; gap: 6px; font-size: 12px; color: #9ba3af; }
.form-grid label.inline { flex-direction: row; align-items: center; gap: 8px; color: #e7eaef; font-size: 13px; }
.actions { display: flex; gap: 8px; justify-content: flex-end; }
.badges { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }
.badges > *:last-child { flex: 1; min-width: 180px; }
</style>

// playgrounds/react-radix/src/App.tsx
import { useState } from 'react'
import {
  Box,
  Button,
  Card,
  Checkbox,
  Flex,
  Grid,
  Heading,
  Progress,
  Select,
  Separator,
  Slider,
  Switch,
  Table,
  Text,
  TextField,
  Badge,
  Callout,
} from '@radix-ui/themes'

const products = [
  { id: 1, name: 'Zeus', status: 'active', price: '$29' },
  { id: 2, name: 'Hermes', status: 'paused', price: '$49' },
  { id: 3, name: 'Atlas', status: 'active', price: '$99' },
]

export default function App() {
  const [name, setName] = useState('')
  const [agree, setAgree] = useState(false)
  const [notify, setNotify] = useState(true)
  const [tone, setTone] = useState<string>('soft')
  const [volume, setVolume] = useState<number[]>([40])

  return (
    <Box p="6" style={{ maxWidth: 960, margin: '0 auto' }}>
      <Flex direction="column" gap="4" mb="5">
        <Heading as="h1" size="7">Annotask × Radix Themes</Heading>
        <Text color="gray">Test-bed for the barrel-export component scanner (Strategy 2).</Text>
      </Flex>

      <Flex direction="column" gap="4">
        <Card>
          <Heading as="h2" size="4" mb="3">Form controls</Heading>
          <Grid columns={{ initial: '1', sm: '2' }} gap="4">
            <Flex direction="column" gap="1">
              <Text as="label" size="2" color="gray">Name</Text>
              <TextField.Root placeholder="Your name" value={name} onChange={(e) => setName(e.target.value)} />
            </Flex>
            <Flex direction="column" gap="1">
              <Text as="label" size="2" color="gray">Button tone</Text>
              <Select.Root value={tone} onValueChange={setTone}>
                <Select.Trigger />
                <Select.Content>
                  <Select.Item value="solid">Solid</Select.Item>
                  <Select.Item value="soft">Soft</Select.Item>
                  <Select.Item value="surface">Surface</Select.Item>
                  <Select.Item value="outline">Outline</Select.Item>
                  <Select.Item value="ghost">Ghost</Select.Item>
                </Select.Content>
              </Select.Root>
            </Flex>
            <Flex gap="2" align="center">
              <Checkbox checked={agree} onCheckedChange={(v) => setAgree(v === true)} />
              <Text size="2">I agree to the terms</Text>
            </Flex>
            <Flex gap="2" align="center">
              <Switch checked={notify} onCheckedChange={setNotify} />
              <Text size="2">Email me on updates</Text>
            </Flex>
            <Flex direction="column" gap="1" style={{ gridColumn: '1 / -1' }}>
              <Text as="label" size="2" color="gray">Volume — {volume[0]}</Text>
              <Slider value={volume} onValueChange={setVolume} min={0} max={100} />
            </Flex>
          </Grid>
          <Separator size="4" my="4" />
          <Flex justify="end" gap="2">
            <Button variant="soft" color="gray">Cancel</Button>
            <Button variant={tone as 'solid'}>Submit</Button>
          </Flex>
        </Card>

        <Card>
          <Heading as="h2" size="4" mb="3">Status indicators</Heading>
          <Flex gap="3" align="center" wrap="wrap">
            <Badge color="iris">Primary</Badge>
            <Badge color="green">Success</Badge>
            <Badge color="amber">Warn</Badge>
            <Badge color="red">Danger</Badge>
            <Box style={{ flex: 1, minWidth: 200 }}>
              <Progress value={volume[0]} />
            </Box>
          </Flex>
          <Callout.Root mt="3">
            <Callout.Text>
              This playground exercises the barrel-exported Radix Themes API — a single
              <code> @radix-ui/themes </code> package with many re-exported components.
            </Callout.Text>
          </Callout.Root>
        </Card>

        <Card>
          <Heading as="h2" size="4" mb="3">Table</Heading>
          <Table.Root>
            <Table.Header>
              <Table.Row>
                <Table.ColumnHeaderCell>ID</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>Name</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>Status</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>Price</Table.ColumnHeaderCell>
              </Table.Row>
            </Table.Header>
            <Table.Body>
              {products.map((p) => (
                <Table.Row key={p.id}>
                  <Table.RowHeaderCell>{p.id}</Table.RowHeaderCell>
                  <Table.Cell>{p.name}</Table.Cell>
                  <Table.Cell>
                    <Badge color={p.status === 'active' ? 'green' : 'amber'}>{p.status}</Badge>
                  </Table.Cell>
                  <Table.Cell>{p.price}</Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table.Root>
        </Card>
      </Flex>
    </Box>
  )
}
