// playgrounds/stress-test/apps/host-single-spa/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'

interface Mfe {
  id: string
  label: string
  stack: string
  hash: string
  mountId: string
}

const contentMfes: Mfe[] = [
  { id: 'vue-data-lab',        label: 'Vue · Data Lab',        stack: 'Vue + FastAPI + Naive UI',      hash: '#/vue',    mountId: 'single-spa-application:@stress/vue-data-lab' },
  { id: 'react-workflows',     label: 'React · Workflows',     stack: 'React + Java + Mantine',        hash: '#/react',  mountId: 'single-spa-application:@stress/react-workflows' },
  { id: 'svelte-streaming',    label: 'Svelte · Streaming',    stack: 'Svelte + Go + bits-ui',         hash: '#/svelte', mountId: 'single-spa-application:@stress/svelte-streaming' },
  { id: 'solid-component-lab', label: 'Solid · Component Lab', stack: 'Solid + Node + Kobalte',        hash: '#/solid',  mountId: 'single-spa-application:@stress/solid-component-lab' },
  { id: 'htmx-partials',       label: 'htmx · Partials',       stack: 'htmx + Rust + Pico.css',        hash: '#/htmx',   mountId: 'single-spa-application:@stress/htmx-partials' },
]

const sidebarMountId = 'single-spa-application:@stress/react-sidebar'

const currentHash = ref(window.location.hash || '#/')
function onHashChange() {
  currentHash.value = window.location.hash || '#/'
}

onMounted(() => window.addEventListener('hashchange', onHashChange))
onUnmounted(() => window.removeEventListener('hashchange', onHashChange))

const isHome = computed(() => currentHash.value === '#/' || currentHash.value === '')

function isActive(hash: string) {
  return currentHash.value === hash || currentHash.value.startsWith(hash + '/')
}
</script>

<template>
  <div class="shell">
    <aside class="sidebar" :id="sidebarMountId" />

    <main class="content">
      <section v-show="isHome" class="overview">
        <div class="overview-inner">
          <h1>Annotask Stress Lab</h1>
          <p class="lede">
            Six MFEs, five backend services, one shell. Pick a route from the
            sidebar to mount its MFE into this pane — each route fills the
            entire content area.
          </p>

          <div class="cards">
            <a v-for="mfe in contentMfes" :key="mfe.hash" :href="mfe.hash" class="card">
              <div class="card-title">{{ mfe.label }}</div>
              <div class="card-stack">{{ mfe.stack }}</div>
              <code class="card-route">{{ mfe.hash }}</code>
            </a>
          </div>
        </div>
      </section>

      <div v-show="!isHome" class="viewport">
        <div
          v-for="mfe in contentMfes"
          v-show="isActive(mfe.hash)"
          :key="mfe.mountId"
          :id="mfe.mountId"
          class="mfe-mount"
        />
      </div>
    </main>
  </div>
</template>

<style scoped>
.shell {
  display: grid;
  grid-template-columns: var(--stress-sidebar-width) 1fr;
  min-height: 100vh;
  background: var(--stress-bg);
  color: var(--stress-text);
  font-family: var(--stress-font);
}

.sidebar {
  background: var(--stress-sidebar-bg);
  border-right: 1px solid var(--stress-sidebar-border);
  min-height: 100vh;
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
}

.content {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.overview {
  flex: 1;
  padding: 48px 48px;
  display: flex;
  align-items: flex-start;
  justify-content: center;
}
.overview-inner { width: 100%; max-width: 1040px; }
.overview h1 { margin: 0 0 10px; font-size: 28px; letter-spacing: -0.02em; }
.lede { color: var(--stress-text-muted); margin: 0 0 28px; font-size: 14px; line-height: 1.6; max-width: 68ch; }

.cards {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 14px;
}
.card {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 18px 20px;
  border: 1px solid var(--stress-border);
  border-radius: var(--stress-radius);
  background: var(--stress-surface);
  color: inherit;
  text-decoration: none;
  transition: border-color 120ms ease, transform 120ms ease, box-shadow 120ms ease;
}
.card:hover {
  border-color: var(--stress-accent);
  transform: translateY(-1px);
  box-shadow: var(--stress-shadow-sm);
}
.card-title { font-size: 15px; font-weight: 600; }
.card-stack { font-size: 12px; color: var(--stress-text-muted); }
.card-route {
  margin-top: auto;
  font-family: var(--stress-font-mono);
  font-size: 12px;
  color: var(--stress-accent);
}

.viewport {
  flex: 1;
  position: relative;
  min-height: 0;
  background: var(--stress-bg);
}
.mfe-mount {
  position: absolute;
  inset: 0;
  overflow: auto;
}

code { font-family: var(--stress-font-mono); }
</style>

// playgrounds/stress-test/apps/mfe-react-sidebar/src/App.tsx
import { useEffect, useState, type ComponentType } from 'react'
import {
  Badge,
  Box,
  Flex,
  Heading,
  IconButton,
  Separator,
  Text,
  Theme,
} from '@radix-ui/themes'
import {
  ActivityLogIcon,
  ComponentInstanceIcon,
  CubeIcon,
  DashboardIcon,
  LayersIcon,
  LightningBoltIcon,
  MoonIcon,
  RocketIcon,
  SunIcon,
} from '@radix-ui/react-icons'
import {
  applyTheme,
  getTheme,
  onThemeChange,
  type StressTheme,
} from '@annotask/stress-ui-tokens'

type IconType = ComponentType<{ className?: string; style?: React.CSSProperties }>

interface NavItem {
  hash: string
  label: string
  stack: string
  icon: IconType
  accent: string
}

const NAV: NavItem[] = [
  { hash: '#/',       label: 'Overview',       stack: 'host shell',        icon: DashboardIcon,          accent: '#5a8dff' },
  { hash: '#/vue',    label: 'Vue · Data Lab',       stack: 'Vue · Naive UI',     icon: CubeIcon,               accent: '#41b883' },
  { hash: '#/react',  label: 'React · Workflows',    stack: 'React · Mantine',    icon: LayersIcon,             accent: '#61dafb' },
  { hash: '#/svelte', label: 'Svelte · Streaming',   stack: 'Svelte · bits-ui',   icon: LightningBoltIcon,      accent: '#ff6a3d' },
  { hash: '#/solid',  label: 'Solid · Components',   stack: 'Solid · Kobalte',    icon: ComponentInstanceIcon,  accent: '#2c7bd0' },
  { hash: '#/htmx',   label: 'htmx · Partials',      stack: 'htmx · Pico.css',    icon: RocketIcon,             accent: '#b964d3' },
  { hash: '#/vue/health', label: 'Services Health',  stack: 'All 5 backends',     icon: ActivityLogIcon,        accent: '#5ad0a7' },
]

function useHash() {
  const [hash, setHash] = useState<string>(
    typeof window === 'undefined' ? '#/' : window.location.hash || '#/',
  )
  useEffect(() => {
    const fn = () => setHash(window.location.hash || '#/')
    window.addEventListener('hashchange', fn)
    return () => window.removeEventListener('hashchange', fn)
  }, [])
  return hash
}

function useStressTheme(): [StressTheme, (t: StressTheme) => void] {
  const [theme, setTheme] = useState<StressTheme>(getTheme())
  useEffect(() => onThemeChange(setTheme), [])
  return [
    theme,
    (next) => {
      applyTheme(next)
      setTheme(next)
    },
  ]
}

export function App() {
  const hash = useHash()
  const [theme, setTheme] = useStressTheme()
  const isDark = theme === 'dark'

  return (
    <Theme
      appearance={isDark ? 'dark' : 'light'}
      accentColor="blue"
      grayColor="slate"
      radius="medium"
      scaling="95%"
      hasBackground={false}
      style={{ height: '100%' }}
    >
      <Flex
        direction="column"
        style={{
          height: '100%',
          color: 'var(--stress-sidebar-text)',
          background: 'var(--stress-surface)',
          padding: '20px 14px',
          gap: 16,
        }}
      >
        <Flex align="center" gap="2" px="2">
          <Box
            style={{
              width: 28,
              height: 28,
              borderRadius: 8,
              background:
                'linear-gradient(135deg, var(--stress-sidebar-accent), #8c5cff)',
              boxShadow: '0 4px 12px rgba(90, 141, 255, 0.35)',
            }}
          />
          <Box>
            <Heading
              as="h1"
              size="3"
              weight="bold"
              style={{ color: 'var(--stress-sidebar-text)', lineHeight: 1 }}
            >
              Annotask
            </Heading>
            <Text
              size="1"
              style={{ color: 'var(--stress-sidebar-text-muted)' }}
            >
              Stress Lab
            </Text>
          </Box>
        </Flex>

        <Separator
          size="4"
          style={{
            background: 'var(--stress-sidebar-border)',
            margin: '4px 0',
          }}
        />

        <Text
          size="1"
          weight="bold"
          style={{
            color: 'var(--stress-sidebar-text-muted)',
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
            padding: '0 8px',
          }}
        >
          MFEs
        </Text>

        <Flex direction="column" gap="1" style={{ flex: 1, minHeight: 0 }}>
          {(() => {
            const activeHash = NAV
              .map((n) => n.hash)
              .filter((h) => hash === h || (h !== '#/' && hash.startsWith(h + '/')))
              .sort((a, b) => b.length - a.length)[0]
            return NAV.map((item) => {
            const active = item.hash === activeHash
            const Icon = item.icon
            return (
              <a
                key={item.hash}
                href={item.hash}
                className={active ? 'nav-link active' : 'nav-link'}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  padding: '10px 12px',
                  borderRadius: 8,
                  textDecoration: 'none',
                  color: active
                    ? 'var(--stress-sidebar-text)'
                    : 'var(--stress-sidebar-text-muted)',
                  background: active
                    ? 'var(--stress-sidebar-surface-2)'
                    : 'transparent',
                  border: '1px solid',
                  borderColor: active
                    ? 'var(--stress-sidebar-border)'
                    : 'transparent',
                  transition: 'background 120ms ease, color 120ms ease',
                }}
              >
                <Box
                  style={{
                    width: 24,
                    height: 24,
                    borderRadius: 6,
                    background: active
                      ? item.accent
                      : 'var(--stress-sidebar-surface)',
                    color: active ? '#0b1220' : item.accent,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flex: '0 0 auto',
                  }}
                >
                  <Icon style={{ width: 14, height: 14 }} />
                </Box>
                <Box style={{ minWidth: 0, flex: 1 }}>
                  <Text size="2" weight={active ? 'bold' : 'medium'} as="div">
                    {item.label}
                  </Text>
                  <Text
                    size="1"
                    as="div"
                    style={{ color: 'var(--stress-sidebar-text-muted)' }}
                  >
                    {item.stack}
                  </Text>
                </Box>
              </a>
            )
            })
          })()}
        </Flex>

        <Separator
          size="4"
          style={{ background: 'var(--stress-sidebar-border)' }}
        />

        <Flex align="center" justify="between" px="2">
          <Flex direction="column" gap="1">
            <Text
              size="1"
              style={{ color: 'var(--stress-sidebar-text-muted)' }}
            >
              Theme
            </Text>
            <Badge
              variant="soft"
              color={isDark ? 'indigo' : 'amber'}
              radius="full"
            >
              {isDark ? 'Dark' : 'Light'}
            </Badge>
          </Flex>
          <IconButton
            aria-label="Toggle theme"
            variant="soft"
            size="3"
            radius="full"
            onClick={() => setTheme(isDark ? 'light' : 'dark')}
            style={{
              background: 'var(--stress-sidebar-surface-2)',
              color: 'var(--stress-sidebar-text)',
              cursor: 'pointer',
            }}
          >
            {isDark ? (
              <SunIcon style={{ width: 18, height: 18 }} />
            ) : (
              <MoonIcon style={{ width: 18, height: 18 }} />
            )}
          </IconButton>
        </Flex>
      </Flex>
    </Theme>
  )
}
